---
- name: Make sure the include line is there in interfaces file
  lineinfile: >
     regexp="^source\ \/etc\/network\/interfaces.d\/\*"
     line="source /etc/network/interfaces.d/*"
     dest=/etc/network/interfaces
     state=present
     insertafter=EOF
  tags: network

- name: Create the directory for interface cfg files
  file: 
    path: '{{ net_path }}'
    state: directory
  tags: network

### ETHERNET

- name: Create the network configuration file for ethernet devices
  template:
    src: 'ethernet_{{ ansible_os_family }}.j2'
    dest: '{{ net_path }}/ifcfg-{{ item.device }}'
  with_items: '{{ network_ether_interfaces }}'
  notify: [ 'Restart Network service' ]
  tags: network

### VLAN

- name: Create the network configuration file for VLAN devices
  template:
    src: 'vlan_{{ ansible_os_family }}.j2'
    dest: '{{ net_path }}/ifcfg-{{ item.device }}'
  with_items: '{{ network_vlan_interfaces }}'
  notify: [ 'Restart Network service' ]
  tags: network
