---

- name: Remove the conflicted packages
  package:
    name: '{{ network__conflict_packages_names|list }}'
    state: absent

- name: Install the required packages
  package:
    name: '{{ network__packages_names|list }}'
    state: present

- name: Ensure state of DHCP client packages
  package:
    name: '{{ network__dhcp_client_packages_names|list }}'
    state: "network__dhcp_enable|ternary('present', 'absent') }}"
