---
# tasks file for network

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Importing initialization tasks
  import_tasks: init.yml
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['network', 'network-install']

- name: Importing configuration tasks
  import_tasks: configure.yml
  tags: ['network', 'network-configure']

- name: Optionally importing facts tasks
  include_tasks: facts.yml
  when: network__facts|bool
  tags: ['network', 'network-facts']
