---
- name: Restart Network service
  service:
    name: "{{ network__service_name }}"
    state: restarted

- name: Restart Network interface
  shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: '{{ ether_result.results }}'
